### PR TITLE
Set material state when restocking jam jar.

### PR DESCRIPTION
**Pull request by Robobeurre**
Hi,

This should make the correct texture appear when jam jars are restocked. Thanks!

### CODE REVIEW

**Comment by Robobeurre** [comment]
Existing restocked jam jars will still have broken textures, but newly restocked ones should be OK.

**Comment by Robobeurre** [comment]
702c939 should address duplicate inventory interactions not only on JamJars but on any restocked item that has an inventory interaction. For instance, harvestables have an "Eat" inventory interaction. Prior to this patch, after removing it from the store shelf, a second "Eat" inventory interaction would be added to the harvestable.

**Comment by Robobeurre** [comment]
Hi,

I'd like to contribute some more changes to Savvier Seller and would like to run the following by you, in order to avoid any duplication of effort and/or conflicting approaches with changes that might already be in the works. I hope this is alright.

I'm considering using the `IExportableContent` interface to handle restocking the items. Since any `GameObject` that can be taken on vacation must be exportable, it seems like a promising way to robustly restock all items. Do you know if this has been tried already and/or if this would be useful?

If the `IExportableContent` approach works, it would also remove the reference to `JamJar` in The Savvier Seller code which should allow the mod to be shipped without including that DLL. Even if that idea doesn't pan out, I think I can remove the `JamJar` dependency with a more in-depth use of reflection (checking the `FullName` property of the `Type` instead of using a cast.)

Let me know what you think. Thanks!

**Comment by Chain-Reaction** [comment]
Hi,

I've actually solved the DLL reference issue so that is not of concern. I've made minor progress on the list of issues I mentioned. Currently I am trying to track down some final issues with the changes making backward compatibility an issue. I don't want to put out a version that is knowingly that broken. I have some ideas and will update if I have success. :)

**Comment by Chain-Reaction** [comment]
Hola,

Just wanted to let you know I apologize for leaving you hanging on this. Unfortunately I have been swamped for the past month or so with making plans to move the NRaas wiki to my network due to our current not meeting our needs and am designing a new site for it. As I'm sure you can respect, this is a massive project considering the amount of data we have on there. This is sucking up most of my modding time. I will definitely get back to you, I just don't know when.

Cheers

**Comment by Robobeurre** [comment]
Hi there,

No worries. There's no rush to look at the restock object idea from February as I've been caught up with other stuff as well--just noticed I didn't even reply to your previous post--sorry! 

Thank you for resolving the DLL reference issue. The canning station mod I've been working on (ask igazor :D ) would have been affected, so you've saved me from some headache. Would love to hear how you did that when things are less hectic.  

Looking forward to the upcoming changes to the NRaas site, which I'm sure is a monster project. Thanks for getting back to me despite the time crunch, I really appreciate it.

**Pull request merged**
