### PR TITLE
JamJar support for The Savvier Seller

### PR DESCRIPTION
**Pull request by Robobeurre**
Hi,

This set of commits fixes issues restocking JamJars (from Grandma's Canning Station premium content) within stores managed by The Savvier Seller.

It works by recognizing that the item being sold is a JamJar. This is done by adding JamJar to the Item enumeration and detecting the type similarly to the other supported types. The RestockItem was modified to add attributes that allow for the storage and recreation of JamJars. Finally the essential attributes of the JamJar are read and then used to recreate the JamJar objects when they are restocked. These attributes are private, hence the use of reflection.

The first commit removes sub-projects from The Savvier Seller, combining all files into a single project. This was done to work around circular dependencies between the main project and sub-projects that seemed unfixable. This also means The Savvier Seller now builds to a single dll whereas the original distribution comprised 3 dlls.

The second commit removes the now unused sub-project folders.

The third commit implements the JamJar support as described above. The patch is large due to code indentation changes.

The final commit fixes a problem creating JamJar objects.

The new dll has been tested by replacing one of the original The Savvier Seller dlls with an override package.

### CODE REVIEW

**Comment by Chain-Reaction** [comment]
Hi and thanks for your contribution!

It looks like you solved several things I intended to so that's much appreciated. However about the JamJar support there appears to be a problem. If a user installs this and doesn't have the store set installed, the game will crash. That is why we haven't built anything to support the latest store releases into the mods. I would hate for your work to go to waste though so perhaps we could just distribute the DLL with the mod. That (hopefully) won't anger EA. Also another thing: did you test what these changes do to existing saves with the mod? I'd imagine it wouldn't be backward compatible.

Do you perchance have an NRaas account so you can release your changes to testing or did you want me to?

**Comment by Robobeurre** [comment]
Hi,

Thanks for taking a look at my changes!

This is my first foray into C# code (from a C++ background) so I'm still very much learning my way around.

I haven't tested what happens with this mod if the store content is not installed (i.e. the `JamJar` class isn't loaded.) You mentioned that the game would crash with this mod if the store content is not installed. Is that due to the `typeof(JamJar)` lookup?

As for users with existing saves, the only persistable game object that is modified is `RestockItem`. I'm assuming that unlike C++, a dynamic language would allow for the member variable layout to change without recompilation, so it should be safe to add members to `RestockItem`. If that's the case, I'm not sure why these changes would be incompatible with prior saves.

I'm unsure of the best approach w.r.t releases. The original mod set included 3 script mods (DLLs) which relied on a sub-project system that I couldn't make work. As a result, this release has only one DLL, which complicates the release procedure (I think.) I don't have an NRaas account at this time; it would be great if you could handle the release (sorry for the trouble.)

**Comment by Chain-Reaction** [comment]
Hi,

Thanks for your response.

It's actually due to the reference to the DLL. At the main menu when all code is loaded, if it cannot find the referenced DLL in any class, the game crashes. You can actually reference classes that aren't loaded as long as the game never accesses the code. Once it does, it crashes then too. 

We are able to modify store content prior to the release of Midnight Hollow because EA merged it into the core. What I'll do in this case is just include the DLL with the release. In the future I'll probably do a core mod that has the newer store content merged into it so it makes things less messy. 

As for backwards compatibility, the game stores the scripting class of objects in them when they are created. This means persistable or not, if you rename the scripting class controlling the object or change it's namespace, the game will delete the object from the world when it cannot load it's stored class. I understand why it was done however, the code was pretty backwards and broken when it was handed over. No worries, if users have to redo their shops that should be fine in exchange for a version of the mod that we can actually get to compile and work on now.

I will get it out for testing as soon as I am able, I don't mind. Thanks for your contribution!

**Comment by Robobeurre** [comment]
Hi,

Thanks for merging the changes.

I was hoping that using `typeof(JamJar)` wouldn't cause a reference to the DLL. The only other place where the `JamJar` object is modified is when saving and loading the properties to/from `RestockItem`. In this case reflection is used, so again, I was hoping that wouldn't cause a reference.

The store content also has significant bugs. For instance, it does not allow for import/export, so it cannot be saved in a lot and placed later, or moved to different maps. I've also fixed that bug, but I'm not sure how to distribute the fixed source code since that is EA's property. I published the fixed DLL for testing here: http://modthesims.info/showthread.php?t=567717.

I haven't renamed any of the classes or namespaces from the original The Savvier Seller mod. Therefore I think the script objects should still work with old saves, although I haven't tested this.

**Comment by Chain-Reaction** [comment]
Hi,

Unfortunately any reference in the code appears to make the game unhappy. It doesn't appear to be much of an issue though, I have distributed the original DLL with the mod and have someone testing it's effects on existing saves. I do see some shifting, peculiarly of the register code, that may make the game drop the persistable objects but I haven't confirmed anything yet. 

As for the other issues, I am aware of those. I have put code into Overwatch to delete the jars if they are corrupt by the processes you noted to stop the Sim menu bouncing that happens once they are. I will grab your DLL and include it as part of the mod rather than the original if that is okay with you. We should probably keep the source of that private just to not anger anyone at EA.

Thanks!

**Comment by Robobeurre** [comment]
Hi,

That's great--thanks for arranging the testing!

> I do see some shifting, peculiarly of the register code, that may make the game drop the persistable objects [...]

I'm afraid I don't quite follow this part. Would you mind explaining it further? I'd like to better understand how the game works.

As to the DLL, you're more than welcome to it. However, there appears to be a bug in the EA code that I'm in the process of investigating (it's a new development on the MTS thread linked above). If my hunch about the bug is correct, the DLL will likely get an update soon. This should not interfere with your testing of Savvier Seller's handling of the jam jars, as the bug in question only affects the HaveJamAndToast interaction. I can drop you a line when/if that update happens, or you can follow the MTS thread--whichever you prefer--just let me know if you would like me to spam you ;-) 

I also plan to add some new functionality to the canning station; the timeline for that is uncertain right now, but I thought it might be prudent to mention it, as some way to sort out the DLL releases will have to be worked out.

Thank you (and the rest of the NRaas team) again for all this work.

**Comment by Chain-Reaction** [comment]
Hi,

There was some shifting of the StoreSetBase and StoreSetRegister namespace. Per tests, it seems this has caused the registers to forget what was for sale. There's also some issues with restocking and the jars restocking empty. Just working on compiling the issues found and seeing if I can quickly solve some of them. I'll let you know more once my tester has reported back if my latest changes resolve some things for existing saves.

Let me know here when the DLL is ready for shipping. I don't have a MTS account. 

Thanks!

**Comment by Robobeurre** [comment]
Sounds good. Thanks for the explanation. I hope the new issues will not be too difficult to resolve--let me know if there's anything I can do. 

The DLL is good to go: http://chii.modthesims.info/getfile.php?file=1587268 Sorry for linking to the .package attachment on the MTS thread instead of attaching it here directly, but I'm not at my computer right now. This revised DLL, in addition to the export-persist fix, addresses a bug that disabled eating toast with jam if the Baker's Station is not installed. The toast interaction is now available on jams regardless of the presence of the bakery oven in the install. 

I've started to work on new functionality for the canning station, but it's unclear when that'll be ready, so I don't want to hold anything up. I'll post here when it drops.

**Comment by Chain-Reaction** [comment]
Just wanted to let you know I'm still working with my tester on this. Unfortunately we are both a bit busy with holiday related actives but I hope to get this out in the new year.

Cheers

**Comment by Chain-Reaction** [comment]
Hope you enjoyed your holidays. I hate to hit you with this wall of text but just wanted to share the results my tester returned with. She's an avid user of the mod so she's thrown in just about everything she knows that was wrong with the mod previously too to get it sorted while we are focusing on the mod. If you want to take a stab at any of it, feel free, otherwise I'll get to it when I have a moment. :)

4. When an active sim is hired as a Clerk through the Register menu "Hire Clerk" option, they autonomously break away from their duties and start buying items from the shop. If I click the interaction from their queue to cancel it, the shopping meter disappears but they swipe the item off the shelf anyway.


5. When an active sim is hired as a Clerk through the Register menu "Hire Clerk", they used to be chained to it, unable to do anything else until I used the "Fire Clerk" option on the Register. Now, the "Tend Shop" interaction drops from their queue and they start doing whatever they feel like. Talk to customers, walk out of the shop, buy goods from the shop (as mentioned above) etc. The "Tend Shop" interaction flashes up in their queue but disappears quickly. Eventually it will stay and the clerk gets summoned back to the Register but it takes too long and seems strange that they are able to do these other things when they're supposed to be tending their shop.


6. When an active sim is directed (from the Register menu) to "Tend Register", they used to be chained to it and were unable to do anything else unless I cancelled the interaction from their queue. Now, I'm able to direct them to do other tasks (like use the toilet etc.) without cancelling the "Tend Register" interaction from their queue because it just disappears. They will complete the task then the "Tend Register" interaction reappears in their queue and they will go back to tending the Register again.


7. When an item needs restocking on the shelf but the Register's inventory has run out of that particular product, I used to hover over the restock item on the shelf and a tool tip would say "Out of Stock" which would be correct. Now, I have the option to "Browse" which is incorrect. If I then change the shelf to "Enable Restock Craftable From Buy Mode", the clerk is able to restock it autonomously (if she is currently the "Hired Clerk") but I only get the "Browse" interaction still.


9. If the active sim is not hired as the clerk, sometimes, when I click on the Restock Item on a shelf, it will only display the "Browse" option instead of the "Restock" option. This happens at random and also occurred in V5. Clicking the "Browse" option results in the same error stated in point 2 above - the notification box is completely blank. If, however, the active sim is hired as the clerk, she is able to restock the item autonomously with no problems.

------------ (Elaborations on 7 and 9)

7) I did word it correctly but let's see if I can clarify...

Active sim is manually set to "Tend Register"

Shelf is left at default setting of restocking from the Register's Inventory

There is stock in the Register's Inventory but not of all products.

Any "Restock Items" on the shelf for products that are not in stock, only have the "Browse" (*) interaction when they should have the greyed out "Restock" interaction (which when hovered over, should display a tooltip stating the product is "Out of stock").

(*) If the store is open, the "Browse" interaction is NOT greyed out.
If the store is closed, the "Browse" interaction IS greyed out.

To answer your question on this point, the restock signs were created with V6.


9) This is definitely related to issue 7 and yes it was broken in V5 as well...

Active sim is "Hired as Clerk"

Shelf is left at default setting of restocking from the Register's inventory

There is stock in the Register's Inventory but not of all products.

All "Restock Items" on the shelf for products that are in stock or not, have both "Browse" and "NRaas" interactions.

If the products are in stock, the clerk restocks them autonomously.

When she starts restocking, the "NRaas" interaction disappears from all "Restock Items".

---------------- Elborations on the other issues

1. Interaction Drops From Queue When Active Sim Is "Hired As Clerk":-

1a. Clerk gets the "Tend Shop > Tend Register" interaction in queue.
The interaction then drops from queue for no reason that I can see.
Register shows 3 customers pending.
Clerk then does what she likes autonomously (including buying her own stock).
The Register's "Tend Register" option is greyed out indicating that she is still hired.
The Register still has the option to fire clerk.
"Tend Shop" interaction eventually re-appears back in active sims queue after a few sim-minutes and she resumes tending the Register.

1b. Customer spoke to clerk and interaction dropped from clerk's queue.
Immediately after their conversation was over, "Tend Register" interaction icon appeared back in clerk's queue and she went back to tend the register.

2. Interaction Drops From Queue When Active Sim Is Manually Directed To "Tend Register":-

2a. Customer sim buys item off a shelf that's higher than their head.
Active sim is manually directed to restock this item.
Interaction drops from queue.
Active sim does what she likes autonomously.

3. Restock Items only showing "Browse" Interaction When Active Sim is "Hired As Clerk":-

3a. Shelf set to Restock from Register's Inventory which contains fruit and vegetables.
Some items have been sold from the shelf and replaced by the Restock Item.
With active sim selected, clicking on Restock Items only brings up the "Browse" interaction.
Active sim is still hired as clerk and can autonomously restock those items.

3b. Shelf set to Restock Craftables from Buy Mode. Products on sale are fruit and vegetables.
Four products have been sold from the shelf and replaced by the Restock Item.
With active sim selected, clicking two of the four Restock Items, only brings up the "Browse" interaction which is incorrect.
The other two Restock Items correctly display the "Restock" interaction.

4. Restock Items only showing "Browse" Interaction When Active Sim is NOT "Hired As Clerk":-

4a. Shelf is set to "Restock Craftable From Buy Mode".
At end of day, all Restock Items correctly had the Restock interaction on them.
Next day, all Restock Items still had the Restock interaction on them and active sim was able to restock them all.

4b. Shelf is left at default of restocking from Register's inventory which contains no products at end of day.
Shop is closed.
Shelf has four Restock Items which only have the greyed out "Browse" interaction.
Next day, when shop is open again, all four Restock Items have the "Browse" interaction and in addition, the "NRaas" interaction, neither of which are greyed out.
Active sim is then "Hired As Clerk" by me.
Restock Items now only have the "Browse" interaction (not greyed out).
Active sim immediately restocks the products for which stock exists in the Register's inventory.

4c. Shop is closed
Shelf set to restock craftable from buy mode.
At end of day, six items have sold and have been replaced by restock item.
All six restock items only have greyed out "Browse" interaction.
Opening Hour has been set to 9am.
Active sim hired as clerk again before 9am.
At 9am, active sim is teleported to shop and begins autonomously restocking the six restock items above.
All six restock items only have the Browse interaction if manually clicked on.

4d. Shop is closed.
Shelf set to restock from Register's inventory.
At end of day there are several restock items left on shelf as Register's inventory is empty.
All restock items only have the greyed out Browse interaction if manually clicked on
Opening Hour has been set to 9am.
Active sim hired as clerk before 9am.
Active sims personal inventory is replenished with more stock.
At 9am, active sim is teleported to shop and begins autonomously restocking the restock items. Game is paused and stock is transferred from active sims personal inventory to the Register's inventory.
Only one restock item is left on shelf because there is none of that item in the Registers inventory.
The one restock item that's left, only has the "Browse" interaction if manually clicked on.

------------------New Issues Noticed:-

5. Send Home After Purchase.
Does not seem to be working. Sims are not being sent home, they remain on the lot and buy again after the cooldown period has passed.

6. The notification about a customer leaving without paying popped up but she was still in the shop in the process of buying another item.

7. Active sim was hired as clerk.
I changed her career outfit via MC > Edit in CAS.
She carried on working afterwards.
A few sim-minutes later I directed her to use the toilet
The "Tend Shop" icon dropped from her queue.
She used the toilet and washed her hands autonomously. She the tried to autonomously read a book from her personal inventory about three times but couldn't complete the interaction.
Approx 5 sim-minutes later, the "Tend Shop" icon reappeared in queue and she was summoned back to the Register which showed 2 customers pending.
Couple of sim-minutes after this she was reset back to her home lot. Notification said:
NRaas.ErrorTrap
ScriptError
Jocasta Bachelor
In her absence, a customer (inactive sim) autonomously paid at the register.
Within 10 sim-minutes, Jocasta was teleported back to tend the register.
ScriptError to be uploaded.

8. The Register seems to get stuck on a certain customer if they are unable to pay for some reason. The Register's number of "Customers Pending" just keeps increasing and it prevents the clerk from restocking. If I use the "Clear Customer Queue" interaction at this point, the clerk starts restocking again straight away.

----------------Other Errors From V5 That Are Still Occurring In V6:-

9. "Shop base null" notification pops up.
Ani has previously told me this is because the mod can't find the item on the shelf.
Occurs whether using the Store's Savvy Seller shelf that Ani included in the mod or third party shelves edited by their creator to work with the Savvier Seller mod.
I think this only happens when selling Buy Mode items though.

10. If you save and exit the game while sims are shopping (with the Shopping Meter visible above their heads), on reload these sims are reset and the following notification pops up for each sim:
"Wait For Turn: Exception of type Sims3.SimIFace.ResetException was thrown."
The Shopping Meter drops into the floor and has to be deleted using TestingCheats and Shift+Click.
The visual glow from the Shopping Meter remains until you next reload the save.

11. When Restocking Fruit and Vegetable products, they do not appear in the same state or position, often hanging underneath the shelf instead of sitting on top of it.

12. When testing two shops on the same lot:-

12a. Active sim is hired as clerk in first shop. An inactive sim is hired as clerk in the second shop.
"Tend Shop" interaction just drops from queue of active sim for no reason.
Active sim then goes to buy an item from second shop.
Active sim gets summoned back to his register in first shop before he has a chance to pay for the item he's bought in second shop.

12b. Active sim is hired as clerk in first shop. An inactive sim is hired as clerk in the second shop.
A second inactive sim swipes an item off a shelf in the first shop then walks into second shop and browses shelves before going back to first shop to pay. 

---------------
Testing V6 with Canned Goods:-

1. Restocking a jar of coffee beans from Buy Mode (with "Restock Craftable From Buy Mode" enabled) produces an empty jar.

2. Restocking a jar of coffee beans from the Register's inventory produces a full jar.

3. Sims are able to be directed to buy the empty jar for sale. Clicking on it does not produce a ScriptError anymore like it did with V5 of the mod. The empty jar gives the visual appearance of being full in the sims inventory. The "Open jar" option appears twice on each jar but the sim is still able to complete the interaction successfully - the beans appear in their inventory in place of the empty jar.

**Comment by Chain-Reaction** [comment]
And it looks like github automatically renamed 7 and 9 in the first list to 4 and 5. :)

**Comment by Robobeurre** [comment]
Happy new year! Sorry for not getting back to you sooner. Many thanks to you and the tester for the new info. Not sure I have the bandwidth to tackle the other issues with this mod right now, but I'll add some observations from my own gameplay in case it helps any (though they're hardly as exhaustive as your awesome tester's).

Issue 3 (from the top of your post): I have not observed this in my game (I think I have V5 of the mod, the latest on the download page). When my active sim is made to "Tend Register", I cannot manually make them go to the bathroom, or even restock the shelves, without first cancelling Tend Register. The bathroom/restock action gets added to the queue, but don't run until Tend Register is cancelled. 

Issue 1 (from *Other Errors From V5 That Are Still Occurring In V6*): I can confirm that for both active sims and NPCs, and third-party display surfaces. Could it be related to the intersect check?

Other issues I've noticed:

* Restock items don't persist between sessions. If I leave a restock item on the shelf and quit the game, at the next session, the item no longer has the Restock interaction, just Browse. The tooltip still displays the purchased object's name, however.

* On occasion, the Restock interaction also disappears from restock items within a single game session. I have not managed to reproduce this consistently nor discern any pattern to its occurrence.

* Sometimes restock items themselves (not the restocked merchandise) spawn in the wrong location. For example, they would appear on the floor beneath a shelf where something was sold, even when the shelf is not close to the floor.

* Active sims autonomously make purchases from their own store (or a store owned by another member of the household). Maybe this behaviour is intended, but it seems counter-intuitive.

***

With regard to the jam jars, I have not been able to reproduce the issue exactly as described, i. e. restock producing an empty jar. Restocking in my game produced a jar with the wrong texture (not empty, but, say, orange jam instead of coffee beans) but correct content. This is caused by RestockItemClassHelper not calling SetMaterialState when it recreates the sold jam jar. I'll provide a fix for this shortly.

I'm currently looking into the multiple "Open Jar" interactions. Sometimes it appears three times...

I'm adding a new type of canned good to the canning station itself, but I'm afraid that cannot be made compatible with Savvier Seller, as including the (further) modded DLL in Savvier Seller would break the canning station for players who do not have the canning station right now but choose to install it at a later date. So the DLL you have now (with the import/export and toast fixes) can be released with the next version of Savvier Seller whenever it's ready. My canning station mod can be put into the Overrides directory for players who want to run both.

**Comment by Chain-Reaction** [comment]
Cheers for your recent commits. I plan to address some of the issues I noted above when I have time and will release a testing version when I have more of them hammered down. :)

**Pull request merged**
